# Generated by Django 5.2.13 on 2026-04-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelStation',
        ),
    ]
